import { expect, test } from '@playwright/test';

test('a public registration reaches active access and the one-time local bootstrap promotes its selected account @emulator', async ({ page }) => {
  const bootstrapCode = process.env.ATHAR_E2E_BOOTSTRAP_CODE;
  if (!bootstrapCode) throw new Error('ATHAR_E2E_BOOTSTRAP_CODE must be generated by the emulator runner.');
  const username = `onboard${Date.now().toString(36)}`;
  const password = 'Temporary-password-123';

  await page.goto('/login');
  await page.getByRole('button', { name: 'Creer un compte' }).click();
  await page.getByLabel('Nom affiche').fill('Onboarding Emulator');
  await page.getByLabel('Identifiant').fill(username);
  await page.getByLabel('Mot de passe').fill(password);
  await page.getByRole('button', { name: 'Creer mon compte' }).click();
  await expect(page.getByRole('heading', { name: 'Zones de Toulouse' })).toBeVisible({ timeout: 20_000 });

  await page.getByRole('button', { name: 'Reglages' }).click();
  const settings = page.getByRole('dialog', { name: 'Reglages' });
  const version = page.getByRole('button', { name: 'Version de l application' });
  for (let tap = 0; tap < 10; tap += 1) await version.click();
  const code = page.getByLabel('Code d activation unique');
  await code.fill(`${bootstrapCode}x`);
  await page.getByRole('button', { name: 'Activer l administration de ce workspace' }).click();
  await expect(settings.getByRole('status')).toContainText(/Invalid bootstrap code|Activation impossible/, { timeout: 60_000 });
  await code.fill(bootstrapCode);
  await page.getByRole('button', { name: 'Activer l administration de ce workspace' }).click();
  await expect(settings.getByRole('status')).toContainText('Administration activee', { timeout: 30_000 });
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: 'Couverture terrain' })).toBeVisible({ timeout: 30_000 });
});
